SKILLS = {
    "attack": {"name": "Attack", "enabled": False},
    "strength": {"name": "Strength", "enabled": False},
    "defence": {"name": "Defence", "enabled": False},
    "ranged": {"name": "Ranged", "enabled": False},
    "prayer": {"name": "Prayer", "enabled": True},
    "magic": {"name": "Magic", "enabled": False},
    "runecraft": {"name": "Runecraft", "enabled": True},
    "hitpoints": {"name": "Hitpoints", "enabled": False},
    "crafting": {"name": "Crafting", "enabled": True},
    "mining": {"name": "Mining", "enabled": True},
    "smithing": {"name": "Smithing", "enabled": True},
    "fishing": {"name": "Fishing", "enabled": True},
    "cooking": {"name": "Cooking", "enabled": True},
    "firemaking": {"name": "Firemaking", "enabled": True},
    "woodcutting": {"name": "Woodcutting", "enabled": True},
    "fletching": {"name": "Fletching", "enabled": True},
    "slayer": {"name": "Slayer", "enabled": False},
    "agility": {"name": "Agility", "enabled": True},
    "thieving": {"name": "Thieving", "enabled": True},
    "herblore": {"name": "Herblore", "enabled": True},
    "farming": {"name": "Farming", "enabled": False},
}